-- MySQL Script generated by MySQL Workbench
-- 06/27/14 17:34:23
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SearchEngine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SearchEngine` ;
CREATE SCHEMA IF NOT EXISTS `SearchEngine` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SearchEngine` ;

-- -----------------------------------------------------
-- Table `SearchEngine`.`MEMBER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SearchEngine`.`MEMBER` ;

CREATE TABLE IF NOT EXISTS `SearchEngine`.`MEMBER` (
  `id` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'member\'s  id (Unique)',
  `password` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'password',
  `email` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'email',
  `level` INT NULL DEFAULT 1 COMMENT 'member level (see in level rule)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `SearchEngine`.`CONTRIBUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SearchEngine`.`CONTRIBUTOR` ;

CREATE TABLE IF NOT EXISTS `SearchEngine`.`CONTRIBUTOR` (
  `id` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'referenced by member.id',
  `upload_count` INT(11) NOT NULL COMMENT 'number of total registered times',
  `url_upload_count` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `f_c_id`
    FOREIGN KEY (`id`)
    REFERENCES `SearchEngine`.`MEMBER` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `SearchEngine`.`URL_DATA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SearchEngine`.`URL_DATA` ;

CREATE TABLE IF NOT EXISTS `SearchEngine`.`URL_DATA` (
  `idx_num` INT(11) NOT NULL COMMENT 'sequence of url',
  `url` VARCHAR(512) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'url',
  `title` VARCHAR(256) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT 'UNKNOWN' COMMENT 'title in url',
  `modified_date` CHAR(64) NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT 'modified by system',
  `registered_date` CHAR(64) NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT 'initial registered date',
  `hit` INT(11) NULL DEFAULT 0 COMMENT 'number of registered url' /* comment truncated */ /*(how many people registered in this url?)*/,
  PRIMARY KEY (`url`),
  UNIQUE INDEX `idx_num_UNIQUE` (`idx_num` ASC))
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `SearchEngine`.`REGISTER_MEMBER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SearchEngine`.`REGISTER_MEMBER` ;

CREATE TABLE IF NOT EXISTS `SearchEngine`.`REGISTER_MEMBER` (
  `url` VARCHAR(512) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'referenced by contributor.url',
  `id` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'referenced by contributor.id',
  PRIMARY KEY (`url`, `id`),
  INDEX `f_rm_id_idx` (`id` ASC),
  CONSTRAINT `f_rm_id`
    FOREIGN KEY (`id`)
    REFERENCES `SearchEngine`.`CONTRIBUTOR` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `f_rm_url`
    FOREIGN KEY (`url`)
    REFERENCES `SearchEngine`.`URL_DATA` (`url`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `SearchEngine`.`CONTRIBUTOR_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SearchEngine`.`CONTRIBUTOR_INFO` ;

CREATE TABLE IF NOT EXISTS `SearchEngine`.`CONTRIBUTOR_INFO` (
  `id` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'referenced by contributor.id',
  `add_url_number` INT(11) NULL DEFAULT 0 COMMENT 'number of url in uploaded bookmark',
  `upload_date` CHAR(64) NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT 'when is bookmark upload time?',
  `browser_type` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'which kinds of bookmark_file type?' /* comment truncated */ /*chrome? IE?*/,
  `bookmark_file` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT 'name of bookmark file',
  INDEX `f_ci_id_idx` (`id` ASC),
  CONSTRAINT `f_ci_id`
    FOREIGN KEY (`id`)
    REFERENCES `SearchEngine`.`CONTRIBUTOR` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
ROW_FORMAT = DYNAMIC;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
